name: MurderMystery
version: '${project.version}'
main: ch.ksrminecraft.murdermystery.MurderMystery
api-version: '1.21'
depend: [RankPointsAPI]

permissions:
  murdermystery.use:
    description: Erlaubt Nutzung von /mm
    default: true

  murdermystery.admin:
    description: Erlaubt Admin-Befehle wie /mm forcestart oder /mm stop
    default: op

  murdermystery.join:
    description: Erlaubt einem Spieler, einer Runde beizutreten
    default: true

  murdermystery.leave:
    description: Erlaubt einem Spieler, eine Runde zu verlassen
    default: true
